<?php

return array (
  	'version' => '6.2.1',
  	'title' => 'Media - Main View',
  	'type' => 'wp-media',
  	'id' => 'bp_wp_media-main',
  	'updated' => 1684240270,
	'columns'=>array(
		'image'=>array(
			'type'=>'column-image',
			'label'=>'Image',
			'width'=>'140',
			'width_unit'=>'px',
			'image_size'=>'cpac-custom',
			'image_size_w'=>'130',
			'image_size_h'=>'130',
			'name'=>'image',
			'label_type'=>''
		),
		'filename'=>array(
			'type'=>'column-file_name',
			'label'=>'Filename',
			'width'=>'',
			'width_unit'=>'',
			'sort'=>'on',
			'name'=>'filename',
			'label_type'=>''
		),
		'image-id'=>array(
			'type'=>'column-postid',
			'label'=>'ID',
			'width'=>'100',
			'width_unit'=>'px',
			'sort'=>'on',
			'name'=>'image-id',
			'label_type'=>'',
			'search'=>'on'
		),
		'alt-text' => array(
			'type' => 'column-alternate_text',
			'label' => 'Alt Text',
			'width' => '25',
			'width_unit' => '%',
			'use_icons' => '',
			'name' => 'column-alternate_text',
			'label_type' => '',
			'edit' => 'on',
			'sort' => 'on',
			'filter'=>'on',
			'filter_label'=>'',
			'bulk-editing' =>'',
			'export' => '',
			'search' => ''
		),
		'date'=>array(
			'type'=>'column-modified',
			'label'=>'Date',
			'width'=>'100',
			'width_unit'=>'px',
			'edit'=>'off',
			'sort'=>'on',
			'filter'=>'on',
			'filter_label'=>'',
			'date_format'=>'F j, Y g:i a',
			'filter_format'=>'monthly',
			'name'=>'date',
			'label_type'=>'',
			'search'=>'on',
		),
		'taxonomy-image-categories'=>array(
			'type'=>'taxonomy-image-categories',
			'label'=>'Categories',
			'width'=>'13',
			'width_unit'=>'%',
			'edit'=>'on',
			'enable_term_creation'=>'on',
			'sort'=>'on',
			'filter'=>'on',
			'filter_label'=>'Categories',
			'name'=>'taxonomy-image-categories',
			'label_type'=>'',
			'search'=>'on'
		),
		'taxonomy-image-tags'=>array(
			'type'=>'taxonomy-image-tags',
			'label'=>'Tags',
			'width'=>'13',
			'width_unit'=>'%',
			'edit'=>'on',
			'enable_term_creation'=>'on',
			'sort'=>'on',
			'filter'=>'on',
			'filter_label'=>'',
			'name'=>'taxonomy-image-tags',
			'label_type'=>'',
			'search'=>'on'
		),
		'parent'=>array(
			'type'=>'parent',
			'label'=>'Attached',
			'width'=>'20',
			'width_unit'=>'%',
			'edit'=>'on',
			'enable_term_creation'=>'',
			'sort'=>'',
			'filter'=>'on',
			'filter_label'=>'',
			'name'=>'parent',
			'label_type'=>'',
			'search'=>'on',
			'bulk-editing' =>'',
		),
		'size'=>array(
			'type'=>'column-dimensions',
			'label'=>'Size',
			'width'=>'115',
			'width_unit'=>'px',
		'export'=>'on',
		'sort'=>'on',
			'name'=>'size',
		)
	),
);