<?php

return array (
  	'version' => '6.2.1',
  	'title' => 'Users - Main View',
  	'type' => 'wp-users',
  	'id' => 'bp_wp_users-main',
  	'updated' => 1684240270, 
	'columns'=>array(
		'username'=>array(
			'type'=>'username',
			'label'=>'Username',
			'width'=>'170',
			'width_unit'=>'px',
			'edit'=>'on',
			'sort'=>'on',
			'name'=>'username',
			'label_type'=>'',
			'filter'=>'on',
			'filter_label'=>'',
			'bulk-editing' =>'',
			'search'=>'on'
		),
		'first_name'=>array(
			'type'=>'column-first_name',
			'label'=>'First Name',
			'width'=>'170',
			'width_unit'=>'px',
			'edit'=>'on',
			'sort'=>'on',
			'name'=>'first_name',
			'label_type'=>'',
			'filter'=>'on',
			'filter_label'=>'',
			'bulk-editing' =>'',
			'search'=>'on'
		),		
		'last_name'=>array(
			'type'=>'column-last_name',
			'label'=>'Last Name',
			'width'=>'170',
			'width_unit'=>'px',
			'edit'=>'on',
			'sort'=>'on',
			'name'=>'last_name',
			'label_type'=>'',
			'filter'=>'on',
			'filter_label'=>'',
			'bulk-editing' =>'',
			'search'=>'on',
		),			
		'display_name'=>array(
			'type'=>'column-display_name',
			'label'=>'Display Name',
			'width'=>'170',
			'width_unit'=>'px',
			'edit'=>'on',
			'sort'=>'on',
			'name'=>'display_name',
			'edit'=>'on',
			'sort'=>'on',
			'filter'=>'on',
			'filter_label'=>'',
			'bulk-editing' =>'on',
			'search'=>'on'
		),		
		'email'=>array(
			'type'=>'email',
			'label'=>'Email',
			'width'=>'200',
			'width_unit'=>'px',
			'edit'=>'on',
			'sort'=>'on',
			'name'=>'email',
			'label_type'=>'',
			'filter'=>'on',
			'filter_label'=>'',
			'bulk-editing' =>'',
			'search'=>'on'
		), 
		'user_registered'=>array(
			'type'=>'column-user_registered',
			'label'=>'Registered',
			'width'=>'130',
			'width_unit'=>'px',
			'date_format'=>'F j, Y g:i a',
			'edit'=>'on',
			'sort'=>'on',
			'filter'=>'on',
			'filter_label'=>'',
			'filter_format'=>'monthly',
			'name'=>'user_registered',
			'label_type'=>'',
			'search'=>'on'
		),
		'role'=>array(
			'type'=>'role',
			'label'=>'Role',
			'width'=>'200',
			'width_unit'=>'px',
			'edit'=>'on',
			'sort'=>'on',
			'name'=>'role',
			'label_type'=>'',
			'filter'=>'on',
			'filter_label'=>'',
			'bulk-editing' =>'',
			'search'=>'on'
		),
		'posts'=>array(
			'type'=>'posts',
			'label'=>'Posts',
			'width'=>'200',
			'width_unit'=>'px',
			'edit'=>'on',
			'sort'=>'on',
			'name'=>'posts',
			'label_type'=>'',
			'filter'=>'on',
			'filter_label'=>'',
			'bulk-editing' =>'',
			'search'=>'on'
		),
	),
);