name: ⚠️ Deploy — Sensitive Sites

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag to deploy (e.g. v41.4)'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        wpe_env:
          - aerialspiral
          - babes2022
          - babescatering
          - babeschickentv
          - bubbas2022
          - ccsoschedule
          - familyairhvac
          - firehousehvac
          - forthefield
          - genemcguire
          - giftcardsmerch
          - gpsplumbing
          - kintec
          - midwestair
          - paradisetat
          - poleaerial
          - piercesonac
          - rovindirec1stg
          - rovindir
          - rovininc
          - spribeyes
          - sweetiepie2stg
    steps:
      - name: Checkout tag ${{ github.event.inputs.tag }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Deploy to ${{ matrix.wpe_env }}
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: ${{ matrix.wpe_env }}
          REMOTE_PATH: "wp-content/themes/battleplantheme/"
          PHP_LINT: TRUE
          CACHE_CLEAR: TRUE
